### ISSUE TITLE
search bar: apostrophe encoding issue

### ISSUE THREAD

**Issue by nikolas** [ccnmtl/compiled#126]
![2018-02-27-133416_379x204_scrot](https://user-images.githubusercontent.com/59292/36747400-f40529d8-1bc2-11e8-862e-b9d429e737ee.png)

`MediaWiki's` displays as `MediaWiki&#39;s`.

**Comment by zmustapha** [comment]
Lunr search doesn't like apostrophes, so, as a fix, I just replace it with `\u2019`. I welcome an automated escape, if anyone wants to volunteer

**Comment by nikolas** [comment]
hmmm, we should probably also update lunr.js here. compiled is still on version 1.0. I'll see if I can get it to 2.1.6.

**Comment by nikolas** [comment]
It looks like that will actually resolve the issue from my initial testing... I'll open a PR in a sec.

**Comment by nikolas** [comment]
This is resolved for now, with zarina's fix.
